<?php
@session_start();
?>
<link rel="stylesheet" href="/ressources/css/all.min.css">
<link rel="stylesheet" href="/ressources/css/index.css">
<link rel="stylesheet" href="/ressources/css/tailwind.css">

<script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js" defer></script>
<script src="ressources/js/tailwind/tailwind.js"></script>

<body class="font-poppins antialiased">
  <div class="flex">
    <div id="view" class="h-full flex flex-row " x-data="{ sidenav: true }">

      <div id="sidebar"
        class=" bg-gray-50 dark:bg-black dark:text-white h-screen md:block shadow-xl w-30 md:w-60 lg:w-60 overflow-x-hidden transition-transform duration-300 ease-in-out px-0"
        x-show="sidenav" @click.away="sidenav = false">
        <div class="space-y-6 md:space-y-10 mt-3 mr-5">
          <div id="profile" class="space-y-3 mt-6">
            <img src="ressources/images/web.svg" alt="Avatar user" class="App-logo w-10 md:w-16 rounded-full mx-auto" />
            <div>
              <h2 class="font-bold text-xs md:text-xl text-center text-orange-700">
                <?php if (isset($_SESSION["Auth"])): ?>
                  <?= $_SESSION["Auth"]["pseudo"] ?>
                <?php endif; ?>
              </h2>
              <p class="text-xs text-black-800 text-center">Master Code Admin</p>
            </div>
          </div>

          <div id="menu" class="flex flex-col space-y-2 pl-4">
            <?php
            if (isset($page) && $page !== "dashboard"): ?>
              <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('dash')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:text-base rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z">
                  </path>
                </svg>
                <span class="dark:text-white">Dashboard</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('dash')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:text-base rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z">
                  </path>
                </svg>
                <span class="dark:text-white">Dashboard</span>
              </a>
            <?php endif; ?>

            <?php if (isset($page) && $page !== "articles"): ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('articles')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M11 17a1 1 0 001.447.894l4-2A1 1 0 0017 15V9.236a1 1 0 00-1.447-.894l-4 2a1 1 0 00-.553.894V17zM15.211 6.276a1 1 0 000-1.788l-4.764-2.382a1 1 0 00-.894 0L4.789 4.488a1 1 0 000 1.788l4.764 2.382a1 1 0 00.894 0l4.764-2.382zM4.447 8.342A1 1 0 003 9.236V15a1 1 0 00.553.894l4 2A1 1 0 009 17v-5.764a1 1 0 00-.553-.894l-4-2z">
                  </path>
                </svg>
                <span class="dark:text-white">Articles</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('articles')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M11 17a1 1 0 001.447.894l4-2A1 1 0 0017 15V9.236a1 1 0 00-1.447-.894l-4 2a1 1 0 00-.553.894V17zM15.211 6.276a1 1 0 000-1.788l-4.764-2.382a1 1 0 00-.894 0L4.789 4.488a1 1 0 000 1.788l4.764 2.382a1 1 0 00.894 0l4.764-2.382zM4.447 8.342A1 1 0 003 9.236V15a1 1 0 00.553.894l4 2A1 1 0 009 17v-5.764a1 1 0 00-.553-.894l-4-2z">
                  </path>
                </svg>
                <span class="dark:text-white">Articles</span>
              </a>
            <?php endif; ?>

            <?php if (isset($page) && $page !== "editor"): ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('editor')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
                  <path fill-rule="evenodd"
                    d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z"
                    clip-rule="evenodd"></path>
                </svg>
                <span class="dark:text-white">Editeur</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('editor')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
                  <path fill-rule="evenodd"
                    d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z"
                    clip-rule="evenodd"></path>
                </svg>
                <span class="dark:text-white">Editeur</span>
              </a>
            <?php endif; ?>

            <?php if (isset($page) && $page !== "message"): ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('message')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path>
                  <path
                    d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z">
                  </path>
                </svg>
                <span class="dark:text-white">Messages</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('message')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path>
                  <path
                    d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z">
                  </path>
                </svg>
                <span class="dark:text-white">Messages</span>
              </a>
            <?php endif; ?>

            <?php if (isset($page) && $page == "category"): ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('category')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z">
                  </path>
                </svg>
                <span class="dark:text-gray-500">Catégorie</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('category')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z">
                  </path>
                </svg>
                <span class="dark:text-white">Catégorie</span>
              </a>
            <?php endif; ?>

            <?php if (isset($page) && $page == "users"): ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('users')
                  ?>"
                class="text-sm font-medium text-white py-2 px-2 bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                  </path>
                </svg>
                <span class="dark:text-white">Users</span>
              </a>
            <?php else: ?>
              <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('users')
                  ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg class="w-6 h-6 fill-current inline-block" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                  </path>
                </svg>
                <span class="dark:text-white">Users</span>
              </a>
            <?php endif; ?>

            <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('viewHome') ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 inline-block">
                  <path d="M10 12.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" />
                  <path fill-rule="evenodd" d="M.664 10.59a1.651 1.651 0 010-1.186A10.004 10.004 0 0110 3c4.257 0 7.893 2.66 9.336 6.41.147.381.146.804 0 1.186A10.004 10.004 0 0110 17c-4.257 0-7.893-2.66-9.336-6.41zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
                </svg>
                <span class="dark:text-white">Voir le site</span>
              </a>
            <a href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('logout') ?>"
                class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-orange-700 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out">
                
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 inline-block">
                <path fill-rule="evenodd" d="M3 4.25A2.25 2.25 0 015.25 2h5.5A2.25 2.25 0 0113 4.25v2a.75.75 0 01-1.5 0v-2a.75.75 0 00-.75-.75h-5.5a.75.75 0 00-.75.75v11.5c0 .414.336.75.75.75h5.5a.75.75 0 00.75-.75v-2a.75.75 0 011.5 0v2A2.25 2.25 0 0110.75 18h-5.5A2.25 2.25 0 013 15.75V4.25z" clip-rule="evenodd" />
                <path fill-rule="evenodd" d="M6 10a.75.75 0 01.75-.75h9.546l-1.048-.943a.75.75 0 111.004-1.114l2.5 2.25a.75.75 0 010 1.114l-2.5 2.25a.75.75 0 11-1.004-1.114l1.048-.943H6.75A.75.75 0 016 10z" clip-rule="evenodd" />
              </svg>

                <span class="dark:text-white">Déconnexion</span>
              </a>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script>
    tailwind.config = {
        darkMode: 'class',
    }
</script>
<script>
    function darkModeListener() {
        document.querySelector("main").classList.toggle("dark");
    }
    document.querySelector("input[type='checkbox']#dark-toggle").addEventListener("click", darkModeListener);
</script>
<script>
  // On page load or when changing themes, best to add inline in `head` to avoid FOUC
if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
  document.documentElement.classList.add('dark')
} else {
  document.documentElement.classList.remove('dark')
}

// Whenever the user explicitly chooses light mode
localStorage.theme = 'light'

// Whenever the user explicitly chooses dark mode
localStorage.theme = 'dark'

// Whenever the user explicitly chooses to respect the OS preference
localStorage.removeItem('theme')
</script>
</body>