<style>
    input:checked~.dot {
        transform: translateX(100%);
        /* background-color: #132b50; */
    }
</style>
<div class="ml-auto ">
    <div class="sticky z-10 top-0 h-16 border-b bg-white lg:py-2.5">
        <div class="px-6 flex items-center justify-between space-x-4 2xl:container">
            <h5 hidden class="pl-6 text-2xl text-black-900 font-bold font-medium lg:block">Dashboard</h5>

            <div class="flex space-x-4">
                <!--search bar -->

                <!--/search bar -->
                <!-- <button aria-label="search" class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200 md:hidden">
                    <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 mx-auto fill-current text-gray-600" viewBox="0 0 35.997 36.004">
                        <path id="Icon_awesome-search" data-name="search" d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z"></path>
                    </svg>
                </button> -->
                <!-- <button aria-label="chat" class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 m-auto text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                    </svg>
                </button> -->
                <!-- <button aria-label="notification"> -->

                <!-- </button> -->


                <a href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('message') ?>" class=" rounded-xl border bg-gray-100 focus:bg-blue-400 active:bg-gray-200">

                    <div class="relative scale-75">

                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 m-auto text-gray-600" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                        </svg>


                        <span class="absolute -top-2 left-4 rounded-full bg-red-500 p-0.5 px-2 text-sm text-red-50">
                            <?php if ($countDay > 99) : ?>
                                +99
                            <?php else : ?>
                                <?= $countDay ?>
                            <?php endif; ?>
                        </span>


                    </div>



                </a>

                <div class="bg-white dark:bg-gray-900 justify-center flex flex-row items-center">
                    <div class="flex flex-row justify-between toggle">
                        <label for="dark-toggle" class="flex items-center cursor-pointer">
                            <div class="relative">
                                <input type="checkbox" name="dark-mode" id="dark-toggle" class="checkbox hidden">
                                <div class="block border-[1px] dark:border-white border-gray-900 w-14 h-8 rounded-full"></div>
                                <div class="dot absolute left-1 top-1 dark:bg-white bg-gray-800 w-6 h-6 rounded-full transition"></div>
                            </div>
                            <div class="ml-3 dark:text-white text-gray-900 font-medium">
                                Dark Mode
                            </div>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>

<script src="ressources/js/tailwind/tailwind.js"></script>
<script src="ressources/js/popper.js"></script>