<!DOCTYPE html>
<html lang="en" class="">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <script src="https://cdn.tailwindcss.com" defer></script> -->
  <script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js" defer></script>
  <script src="ressources/js/tailwind/tailwind.js"></script>
  <link rel="shortcut icon" href="ressources/images/web.svg" />
  <link href='ressources/css/froola.css' rel='stylesheet' type='text/css' />
  <title>Genius</title>

  <style>
    .App-logo {
      pointer-events: none;
    }

    @media (prefers-reduced-motion: no-preference) {
      .App-logo {
        animation: App-logo-spin infinite 10s linear;
      }
    }


    @keyframes App-logo-spin {
      from {
        transform: rotate(0deg);
      }

      to {
        transform: rotate(360deg);
      }
    }

    .animated {
      -webkit-animation-duration: 1s;
      animation-duration: 1s;
      -webkit-animation-fill-mode: both;
      animation-fill-mode: both;
    }

    .animated.faster {
      -webkit-animation-duration: 500ms;
      animation-duration: 500ms;
    }

    .fadeIn {
      -webkit-animation-name: fadeIn;
      animation-name: fadeIn;
    }

    .fadeOut {
      -webkit-animation-name: fadeOut;
      animation-name: fadeOut;
    }

    @keyframes fadeIn {
      from {
        opacity: 0;
      }

      to {
        opacity: 1;
      }
    }

    @keyframes fadeOut {
      from {
        opacity: 1;
      }

      to {
        opacity: 0;
      }
    }
  </style>

</head>
<main>

  <div class="flex w-screen">
    <aside>
      <?php
      $page = "articles";
      include_once "../App/Views/admin/partials/navbar/nav-left.phtml";
      ?>
    </aside>
    <div class="w-full flex flex-col">
      <div>
        <header class="">
          <?php
          include_once "../App/Views/admin/partials/navbar/nav-top.phtml"
          ?>
        </header>
        <div class="sample">
          <div class="bg-white max-w-full pt-12 pr-0 pb-12 pl-0 mt-0 mr-auto mb-0 ml-auto sm:py-16 lg:py-20">

            <div class="pt-0 pr-4 pb-0 pl-4 mt-0 mr-auto mb-0 ml-auto max-w-full sm:px-6 lg:px-8">

              <div class="flex w-full px-4 py-6 justify-end justify-items-center items-center gap-4 justify-self-end pr-6">
                <form action="" class="">
                  <input type="text" id="search" placeholder="Search">
                </form>


                <button class="delete bg-red-700 pt-2 pr-6 pb-2 pl-6 text-lg font-medium text-white transition-all duration-200 hover:bg-gray-700 rounded-lg">Supprimer</button>
                <button class="update bg-orange-700 pt-2 pr-6 pb-2 pl-6 text-lg font-medium text-white transition-all duration-200 hover:bg-gray-700 rounded-lg">Modifier</button>
                <button onclick="openModal()" class="update bg-green-700 pt-2 pr-6 pb-2 pl-6 text-lg font-medium text-white transition-all duration-200 hover:bg-gray-700 rounded-lg">Ajouter</button>
                <div class="flex justify-items-center items-center">
                  <label for="all_checked">Tout cocher</label>
                  <input type="checkbox" id="all_checked">
                </div>

              </div>

              <div class="max-w-full px-4">
                <div class="flex flex-col">
                  <div class="overflow-x-auto shadow-md sm:rounded-lg">
                    <div class="inline-block min-w-full align-middle">
                      <div class="overflow-hidden ">
                        <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-700">
                          <thead class="bg-gray-100 dark:bg-gray-700">
                            <tr>

                              <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                Titre de l'article
                              </th>
                              <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                Likes&Commentaires
                              </th>
                              <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                Créer depuis
                              </th>
                              <th scope="col" class="py-3 px-6 text-xs font-medium tracking-wider text-left text-gray-700 uppercase dark:text-gray-400">
                                Modifier depuis
                              </th>
                              
                              <th scope="col" class="p-4">
                                <div class="flex items-center">
                                  <input id="checkbox-all" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                  <label for="checkbox-all" class="sr-only">checkbox</label>
                                </div>
                              </th>
                            </tr>
                          </thead>
                          <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
                            <?php foreach ($allArticles as $key => $values) : ?>
                              <tr class="hover:bg-gray-100 dark:hover:bg-gray-700">

                                <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white"><?= $values["article_title"] ?></td>
                                <td class="py-4 px-6 text-sm font-medium text-gray-500 whitespace-nowrap dark:text-white">
                                  <span>0 comments</span><br>
                                  <span>0 likes</span>
                                </td>
                                <td class="py-4 px-6 text-sm font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                  <?php if ($values["updated_at"] == null) : ?>
                                    <p class="text-gray-900 whitespace-no-wrap">---</p>
                                  <?php else : ?>
                                    <p class="text-gray-900 whitespace-no-wrap">
                                      Le
                                      <?= $values["updated_at"] ?> par
                                      <span class="text-lg font-bold text-gray-800 truncate mb-2 p-2 w[50%k]">
                                        <?= $values["user_pseudo"] ?>
                                      </span>
                                    </p>
                                  <?php endif; ?>
                                </td>

                                <td class="py-4 px-6 text-sm font-medium text-gray-500 whitespace-nowrap dark:text-white">
                                  <input type="checkbox" name="user_select" class="clique" value="<?= $this->datacrypt($values["article_id"]) ?>">
                                </td>

                                <td class="p-4 w-4">
                                  <div class="flex items-center">
                                    <input id="checkbox-table-1" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                    <label for="checkbox-table-1" class="sr-only">checkbox</label>
                                  </div>
                                </td>
                              </tr>
                            <?php endforeach; ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="main-modal fixed w-full h-100 inset-0 z-50 overflow-hidden flex justify-center items-center animated fadeIn faster" style="background: rgba(0,0,0,.7);">
                <div class="border border-teal-500 shadow-lg modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
                  <div class="modal-content py-4 text-left px-6">
                    <!--Title-->
                    <div class="flex justify-between items-center pb-3">
                      <p class="text-2xl font-bold">Ajouter d'articles</p>
                      <div class="modal-close cursor-pointer z-50">
                        <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                          <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z">
                          </path>
                        </svg>

                      </div>
                    </div>
                    <!--Body-->
                    <div class="my-5">
                      <h3 class="mb-2">Selectionnez une catégorie pour votre article</h3>
                      <select name="categorie" id="categorie">
                        <option value="defaut">Choisir une categorie d'article</option>
                        <?php foreach ($allCategories as $key => $values) : ?>
                          <option value=<?= $values["category_id"] ?>> <?= $values["category_name"] ?></option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                    <!--Footer-->
                    <div class="flex justify-end pt-2">
                      <button class="focus:outline-none modal-close px-4 bg-gray-400 p-3 rounded-lg text-black hover:bg-gray-300">Cancel</button>
                      <button class="redirect focus:outline-none px-4 bg-orange-700 p-3 ml-3 rounded-lg text-white hover:bg-blue-700">Aller sur l'éditeur</button>
                    </div>
                  </div>
                </div>
              </div>


</main>
<script>
  const modal = document.querySelector('.main-modal');
  const closeButton = document.querySelectorAll('.modal-close');

  const modalClose = () => {
    modal.classList.remove('fadeIn');
    modal.classList.add('fadeOut');
    setTimeout(() => {
      modal.style.display = 'none';
    }, 500);
  }

  const openModal = () => {
    modal.classList.remove('fadeOut');
    modal.classList.add('fadeIn');
    modal.style.display = 'flex';
  }

  for (let i = 0; i < closeButton.length; i++) {

    const elements = closeButton[i];

    elements.onclick = (e) => modalClose();

    modal.style.display = 'none';

    window.onclick = function(event) {
      if (event.target == modal) modalClose();
    }
  }
</script>
<script>
    tailwind.config = {
        darkMode: 'class',
    }
</script>
<script>
    function darkModeListener() {
        document.querySelector("main").classList.toggle("dark");
    }
    document.querySelector("input[type='checkbox']#dark-toggle").addEventListener("click", darkModeListener);
</script>
<script src="/ressources/js/article_js.js"></script>
<script src="/ressources/js/search.js"></script>