<!DOCTYPE html>
<!--
Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
-->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
	<title>CKEditor 5 </title>
</head>
<body>

<form method="post">
    <textarea id="mytextarea" rows="120">Hello, World!</textarea>
  </form>

  <script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea',
	language: 'fr',
  	language_url: '/ressources/js/langs/fr',
  	plugins: '/ressources/js/plugins/image',
  	external_plugins: {
    	'myplugin': '/js/myplugin/plugin.min.js'
  	}
  });
  </script>
</body>
</html>
