<div class="w-full mx-auto bg-white px-5 py-4 text-gray-600 mb-10">
        <div class="text-center max-w-xl mx-auto">
            <h1 class="text-5xl md:text-6xl font-bold mb-5">Catégorie</h1>
            <h3 class="text-xl font-medium mb-10">Ajouter et supprimer les catégories d'article</h3>
        </div>
</div>


  
<div class="md:px-32 w-full">
  <div class="shadow overflow-hidden rounded border-b border-gray-200">
    <table class="min-w-full bg-white">
      <thead class="bg-gray-800 text-white">
        <tr>
          <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Nom</th>
          <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Bref présentation</th>
          <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Actions</th>
        </tr>
      </thead>
    <tbody class="text-gray-700">
    <?php foreach($allCategories as $key => $values) : ?>
      <tr>
        <td class="w-1/3 text-left py-3 px-4"><?= $values["category_name"] ?></td>
        <td class="w-1/3 text-left py-3 px-4"> <?= $values["category_description"] ?></td>
        <td class="text-left py-3 px-4">
        <button type="button" class="delete_category inline-block px-4 py-1.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true" value="<?= $values["category_id"] ?>">Supprimer</button>
        <button type="button" class="modify_category inline-block px-4 py-1.5 bg-orange-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true" value="">Modifier</button>
        </td>
      </tr>
      <tr>
  
      </tr>
    <?php endforeach; ?>

    <form action="?goto=<?= $this->datacrypt('CategoryController') ?>&action=<?= $this->datacrypt('addCategory')
                    ?>" method="post" class=" border-purple-600">

      <tr>
        <td class="w-1/3 text-left py-3 px-4">
          <input id="category_name" class="font-medium text-orange-600 hover:text-purple-700 focus:text-purple-800 focus:border-orange-600 duration-300 transition ease-in-out text-sm py-3" placeholder="Nom de la nouvelle catégorie"/>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
          <textarea class="text-balack-700 mb-6 pr-3" name="category_description" id="category_description" cols="45" rows="2" placeholder="Taper un petit commentaire pa rapport a cette nouvelle catégorie"></textarea>
        </td>
        <td class="text-left py-3 px-4">
        <button type="submit" id="validation_category" class="inline-block px-4 py-1.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true">Ajouter</button>
        </td>
      </tr>

  </form>
    </tbody>
    </table>

   
  </div>
</div>
<script src="/ressources/js/category.js"></script>

