<div class="bg-white p-8 rounded-md w-full">
	<div class=" flex items-center justify-between pb-6">
		<div>
			<h2 class="text-gray-600 font-semibold">Liste des utilisateurs</h2>
			<span class="text-xs">Tous les utilisateurs</span>
		</div>
		<div class="flex items-center justify-between">
			<form action="" class="flex bg-gray-50 items-center p-2 rounded-md">
				<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20"
					fill="currentColor">
					<path fill-rule="evenodd"
						d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
						clip-rule="evenodd" />
				</svg>
				<input class="bg-gray-50 outline-none ml-1 block " type="text" id="search" placeholder="search...">
			</form>
			<div class="lg:ml-40 ml-10 space-x-8">
				<button
					class="update bg-orange-600 px-4 py-2 rounded-md text-white font-semibold tracking-wide cursor-pointer">Modifier</button>
				<button
					class="delete bg-orange-600 px-4 py-2 rounded-md text-white font-semibold tracking-wide cursor-pointer">Supprimer</button>
				<button class="bg-orange-600 px-4 py-2 rounded-md text-white font-semibold tracking-wide cursor-pointer"
					id="all_checked">Tout cocher</button>
			</div>
		</div>
	</div>
	<div>
		<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
			<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
				<table class="table-fetch min-w-full leading-normal" id="myTable">
					<thead>
						<tr>
							<th
								class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
								Pseudo
							</th>
							<th
								class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
								Role
							</th>
							<th
								class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
								Utilisateur depuis
							</th>
							<th
								class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
								Modifié depuis
							</th>
							<th
								class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider text-center">
								cocher
							</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($allUsers as $key => $values): ?>
							<tr>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<div class="flex items-center">
										<div class="flex-shrink-0 w-10 h-10">
											<img class="w-full h-full rounded-full"
												src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.2&w=160&h=160&q=80"
												alt="" />
										</div>
										<div class="ml-3">
											<p class="text-gray-900 whitespace-no-wrap">
												<?= $values["user_pseudo"] ?>
											</p>
										</div>
									</div>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<?php if ($values["user_role"] == 0): ?>
										<p class="text-gray-900 whitespace-no-wrap">Adminstrateur</p>
									<?php else: ?>
										<p class="text-gray-900 whitespace-no-wrap">Utilisateur</p>
									<?php endif; ?>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<p class="text-gray-900 whitespace-no-wrap">
										<?= $values["created_at"] ?>
									</p>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<?php if ($values["updated_at"] == null): ?>
										<p class="text-gray-900 whitespace-no-wrap">---</p>
									<?php else: ?>
										<?php if ($values["user_role"] == 0): ?>
											<p class="text-gray-900 whitespace-no-wrap">Le
												<?= $values["updated_at"] ?> en compte Adminstrateur
											</p>
										<?php else: ?>
											<p class="text-gray-900 whitespace-no-wrap">Le
												<?= $values["updated_at"] ?> en compte Utilisateur
											</p>
										<?php endif; ?>
									<?php endif; ?>
								</td>

								<td class="ml-50 px-3 py-5 border-b border-gray-200 bg-white text-sm text-center">
									<input type="checkbox" name="user_select" class="clique"
										value="<?= $this->datacrypt($values["user_id"]) ?>">
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<!-- test -->

<!-- test -->
<script src="/ressources/js/users_js.js"></script>
<script src="/ressources/js/search.js"></script>