<?php include_once("../App/Views/components/header.php")?>
<body>
	

	<section class=" max-h-screen dark:bg-gray-900">
		<div
			class="bg-orange grid max-w-screen-xl px-10 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 px-8 py-16">
			<div class="mr-auto place-self-center lg:col-span-7">
				<h1
					class="max-w-2xl mb-4 text-4xl font-extrabold leading-none md:text-6xl xl:text-6xl dark:text-white text-orange-800 text-justify">Un
					des meilleurs blogs dans le domaine du developpement web.</h1>
				<p
					class="max-w-2xl mb-6 font-light text-black-800 lg:mb-8 md:text-lg xl:text-2xl lg:text-xl dark:text-gray-400 text-justify">Que
					vous soyez developpeur web junior, senior ou expert avec des années
					d'expériences, vous decouvrirez forcément une nouvelle facette du
					codage sur le web a travers ce blog.</p>
				<a href="#"
					class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-orange-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
					Commencer <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor"
						viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd"
							d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
							clip-rule="evenodd"></path></svg>
				</a> <a href="#"
					class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
					Rechercher un article </a>
			</div>
			<div class="block lg:mt-0 lg:col-span-5  lg:flex">
			<div class="w-full">
				<div class="w-full shadow-2xl subpixel-antialiased rounded h-full bg-black border-black mx-auto">
					<div class="flex items-center h-6 rounded-t bg-gray-100 border-b border-gray-500 text-center text-black" id="headerTerminal">
					<div class="flex ml-2 items-center text-center border-red-900 bg-red-500 shadow-inner rounded-full w-3 h-3" id="closebtn">
					</div>
					<div class="ml-2 border-yellow-900 bg-yellow-500 shadow-inner rounded-full w-3 h-3" id="minbtn">
					</div>
					<div class="ml-2 border-green-900 bg-green-500 shadow-inner rounded-full w-3 h-3" id="maxbtn">
					</div>
					<div class="mx-auto pr-16" id="terminaltitle">
						<p class="text-center text-sm">Terminal</p>
					</div>

					</div>
					<div class="pl-1 pt-1 h-auto  text-green-200 font-mono text-xs bg-black" id="console">
					<p class="pb-1 text-white text-[1rem] leading-relaxed"> <span class="text-rose-500 p-0 m-0" style="letter-spacing: 0.05rem;">User</span>  :Je veux arreter l'execution d'une boucle meme si toutes les itérations n'ont pas été éffectuées? 
						Pouvez-vous m'aider?
					</p>
					<p class="pb-1 text-white text-[1rem] leading-relaxed "> <span class="text-rose-500 p-0 m-0" style="letter-spacing: 0.05rem;">Codeur INFO</span> : Avec le mot clé break, vous pouvez arreter l'xécution de votre boucle a n'importe quel itération. Pour decouvrir 
					en profondeur le mystere du code informatique , consultez notre blog. 
					</p>
					</div>
				</div> 
				</div>
			</div>
		</div>
	</section>



	<section class="bg-gray-50 dark:bg-gray-800">
		<div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
			<div class="max-w-screen-md mb-8 lg:mb-16">
				<h2
					class="mb-4 text-4xl font-extrabold text-gray-900 dark:text-white">Concu
					par les codeurs pour les passionnés du developpement web comme vous</h2>
				<p class="text-gray-500 sm:text-xl dark:text-gray-400">Genius
					Blog apporte des reponses concretes aux questions que la plupart
					des codeurs se posent et qui ont rapport avec la programmation
					informatique dans la catégorie du web.</p>
			</div>


			<section class="text-gray-600 body-font">
				<div class="container px-5 py-5 mx-auto">
					<div class="flex flex-wrap -m-4">
						<!--start here-->
						<?php include("../App/Views/components/article-home.php")?>
						<?php include("../App/Views/components/article-home.php")?>
						<?php include("../App/Views/components/article-home.php")?>
						<!--End here-->
					</div>
				</div>
			</section>
		</div>



	</section>


<!-- 
  Date : April 14, 2022
  Author : Saad Hasan
  Github : https://github.com/saadh393
  Title : Responsive Grid Layout
  External Plugin : None

 -->

 <section class=" w-screen bg-gradient-to-br from-gray-50 to-gray-100 p-8">
    <h1 class="text-center italic font-bold text-4xl text-rose-500">	TOP 3 des meilleurs articles </h1>

    <div class="grid justify-center w-[80%] mx-auto md:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-7 my-10">
        <!-- Card 1 -->
        <div class="bg-white rounded-lg border shadow-md max-w-xs md:max-w-none overflow-hidden">
            <img class="h-56 lg:h-60 w-full object-cover" src="https://images.unsplash.com/photo-1523289217630-0dd16184af8e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8d29tZW4lMjBlbXBvd2VybWVudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" alt="" />
            <div class="p-3">
                <span class="text-sm text-primary">November 19, 2022</span>
                <h3 class="font-semibold text-xl leading-6 text-gray-700 my-2">
                International Women's Day 2022: Date, history, significance, theme this year
                </h3>
                <p class="paragraph-normal text-gray-600">
                Happy Women's Day 2022: Read on to know all about the history and significance...
                </p>
                <a class="mt-3 block" href="#">Read More >></a>
            </div>
        </div>

        <!-- Card 2 -->
        <div class="bg-white rounded-lg border shadow-md max-w-xs md:max-w-none overflow-hidden">
            <img class="h-56 lg:h-60 w-full object-cover" src="https://images.unsplash.com/photo-1607748862156-7c548e7e98f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHdvbWVuJTIwZW1wb3dlcm1lbnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="" />
            <div class="p-3">
                <span class="text-sm text-primary">November 19, 2022</span>
                <h3 class="font-semibold text-xl leading-6 text-gray-700 my-2">
                International Women's Day 2022: Date, history, significance, theme this year
                </h3>
                <p class="paragraph-normal text-gray-600">
                Happy Women's Day 2022: Read on to know all about the history and significance...
                </p>
                <a class="mt-3 block" href="#">Read More >></a>
            </div>
        </div>


        <!-- Card 4 -->
        <div class="bg-white rounded-lg border shadow-md max-w-xs md:max-w-none overflow-hidden">
            <img class="h-56 lg:h-60 w-full object-cover" src="https://images.unsplash.com/photo-1621352404112-58e2468993a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fHdvbWVuJTIwZW1wb3dlcm1lbnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" alt="" />
            <div class="p-3">
                <span class="text-sm text-primary">November 19, 2022</span>
                <h3 class="font-semibold text-xl leading-6 text-gray-700 my-2">
                International Women's Day 2022: Date, history, significance, theme this year
                </h3>
                <p class="paragraph-normal text-gray-600">
                Happy Women's Day 2022: Read on to know all about the history and significance...
                </p>
                <a class="mt-3 block" href="#">Read More >></a>
            </div>
        </div>



	</div>
</section>



	<?php include_once("../App/Views/components/footer.php")?>
</body>
</html>